version: "3.8"

services:
  backend:
    container_name: backend
    image: gobyungyong/calendar_back
    env_file:
      - ./.env
    ports:
      - 8000:8000

  frontend:
    image: gobyungyong/calendar_front
    volumes:
      - build_folder:/app/build

  nginx:
    container_name: nginx
    image: gobyungyong/calendar_nginx
    ports:
      - 80:80
    volumes:
      - build_folder:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
volumes:
  build_folder:
