name: back deploy

on:
  push:
    paths:
      - 'Gobyungyong/calendar_test/calendar_back/**'
  pull_request:
    paths:
      - 'Gobyungyong/calendar_test/calendar_back/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_IP}}
          username: ${{secrets.SSH_ID}}
          password: ${{secrets.REMOTE_SSH_KEY}}
          port: ${{secrets.REMOTE_SSH_PORT}}
          script: |
            cd calendar_test
            git pull origin main
